server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://fincore-postgres:5432/fincore
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://fincore-eureka-server:8761/eureka

jwt:
  secret: fincore-secret-key-fincore-secret-key
  expiration: 3600000
